[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://records-gmox.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
